### ISSUE TITLE
Crear shell del app - React Native

### ISSUE THREAD

**Issue by umartinez22** [Emplea-do/MobileApp-ReactNative#1]
Como Software Developer crear el shell principal del app, este debe tener los basico a nivel de navegación.

Criterios de Aceptación:

- Crear tabs (Ajustes, Buscar, Perfil).
- Configurar navegación entre las diferentes vista.

**Comment by ielijose** [comment]
Resolved in #9

**Comment by ielijose** [comment]
Resolved in #9
