### ISSUE TITLE
Crear un Pull Request Template en ambos repositorios.

### ISSUE THREAD

**Issue by claudiosanchez** [Emplea-do/MobileApp-ReactNative#12]
Copiar este archivo a los dos repositorios para tener un Pull Request Template. 

Prestar atención a la ruta del archivo. Debe de estar en un folder en el root del repo llamado .github

 https://github.com/Emplea-do/emplea_do/blob/development/.github/pull_request_template.md

**Comment by cvivieca** [comment]
Esto fue resuelto con el pull request #13
