### ISSUE TITLE
Crear proyecto "File New" para React Native.

### ISSUE THREAD

**Issue by umartinez22** [Emplea-do/MobileApp-ReactNative#6]
Crear un nuevo proyecto con React Native cli.

**Criterio de aceptación:**

- Debe de tener la siguiente estructura de docs/*
android/*
ios/*
src/*[react-native-files]
README.md

**src/** Contendría lo siguiente:

src/
-- assets/
-- services/
-- components/
-- tools/
-- views/

**Comment by ielijose** [comment]
Resolved in #8
